### PR TITLE
attention mask needs to account for variable text context length too

### PR DESCRIPTION
**Pull request by lucidrains**

### CODE REVIEW

**Comment by lucidrains** [comment]
@rom1504 ah sorry, forgot about the attention mask too :pray:

**Comment by rom1504** [comment]
I am honestly not sure if we should do this at all

why isn't it a problem for every other use ?

I feel diverging from upstream on this is not good

why not instead change something in dalle2 side ?

**Comment by lucidrains** [comment]
@rom1504 it has already diverged in other projects https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/transformer.py#L609 the need was always there for flexible text length

**Comment by lucidrains** [comment]
@rom1504 yea i could, but here the issue is strictly with the original code not being flexible enough in how it handled the text sequence length dimension

**Comment by lucidrains** [comment]
@rom1504 this should be the last change! :pray:

**Comment by rom1504** [comment]
ok note another option would be to just use openclip even for using openai clip (it supports it)

**Comment by lucidrains** [comment]
@rom1504 yea, that's true, especially now that you all have achieved a new SOTA :pray: ! i should probably just remove the openai ones

**Comment by lucidrains** [comment]
@rom1504 thank you for dealing with this :pray:

**Pull request merged**
